import psycopg2


SQL_CREATE_TABLE_CUSTOMER = """
CREATE TABLE IF NOT EXISTS customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(100)
);
"""

SQL_CREATE_TABLE_PRODUCT = """
CREATE TABLE IF NOT EXISTS product (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price REAL NOT NULL
);
"""

SQL_CREATE_TABLE_ORDER = """
CREATE TABLE IF NOT EXISTS "order" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT REFERENCES customer(id),
    quantity INT NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    time TIMESTAMP WITHOUT TIME ZONE NOT NULL
)
"""

SQL_CREATE_TABLE_ORDER_DETAIL = """
CREATE TABLE IF NOT EXISTS order_detail (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT REFERENCES "order"(id),
    product_id INT REFERENCES product(id),
    quantity INT NOT NULL,
    price DOUBLE PRECISION NOT NULL
);
"""


if __name__ == "__main__":
    with psycopg2.connect(
        database="postgres",
        host="localhost",
        port="5432",
        user="postgres",
        password="",
    ) as conn:
        cursor = conn.cursor()
        cursor.execute(SQL_CREATE_TABLE_CUSTOMER)
        cursor.execute(SQL_CREATE_TABLE_PRODUCT)
        cursor.execute(SQL_CREATE_TABLE_ORDER)
        cursor.execute(SQL_CREATE_TABLE_ORDER_DETAIL)
        conn.commit()

